from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected 1 match, got {count}")
    return text.replace(old, new, 1)

# DockLiquidGlassView: make HOME settle depend on a real focus-loss/visible-recents
# transition, not merely GestureToHome (which is also emitted for a small HOME Dock
# pull that springs back).
p = Path("src/main/java/com/hellovoid/liquiddock/DockLiquidGlassView.java")
s = p.read_text(encoding="utf-8")

s = replace_once(s,
'''    private boolean launcherResumed;\n    private boolean launcherLifecycleKnown;\n    private boolean windowVisible;\n''',
'''    private boolean launcherResumed;\n    private boolean launcherLifecycleKnown;\n    // Set only by the real Launcher window-focus hook.  This intentionally does not\n    // follow sceneState.desired(): a short HOME Dock pull can pre-arm RECENTS at 8dp\n    // even though Launcher never left the foreground.\n    private boolean launcherWasAway;\n    private boolean homeReturnTransitionArmed;\n    private long homeSettleGeneration;\n    private boolean windowVisible;\n''',
"focus transition fields")

s = replace_once(s,
'''        sceneState.setGestureTarget(target, System.nanoTime());\n        // GestureToHome is emitted before launcher focus while Dock icons are still\n        // flying into place.  Open the settle window here, but do not block the normal\n        // capture scheduler: cached HOME wallpaper crops remain fully live.\n        if ("HOME".equals(target)) {\n            beginHomeSettle("gesture-home");\n        }\n        updateDesiredScene();\n''',
'''        // GestureToHome is also emitted when a small Dock pull on HOME is released.\n        // sceneState.desired() cannot distinguish that case because the 8dp recents\n        // pre-arm may already have changed desired to RECENTS.  A real APP -> HOME\n        // return must have lost Launcher window focus; a real RECENTS -> HOME return\n        // has the overview actually visible.\n        boolean realHomeReturn = "HOME".equals(target)\n                && (launcherWasAway || isRecentsVisible());\n        sceneState.setGestureTarget(target, System.nanoTime());\n        if (realHomeReturn) {\n            armHomeSettle("gesture-home");\n        } else if ("HOME".equals(target)) {\n            // HOME-local spring-back: remove any stale transition timer immediately.\n            // The normal observation/capture cadence below remains untouched.\n            cancelHomeSettle("gesture-home-local");\n            logI("home settle bypass: HOME-local Dock gesture");\n        } else {\n            // Gesture was interrupted toward APP/RECENTS; any pending HOME tail frame\n            // is now stale and must never land later as a visible flash.\n            cancelHomeSettle("gesture-" + target.toLowerCase(java.util.Locale.ROOT));\n        }\n        updateDesiredScene();\n''',
"scene-aware gesture settle")

s = replace_once(s,
'''    /** Public entry for MainHook: launcher gained focus (returning home).  The Dock\n     *  collapse animation may paint icon ghosts into an in-flight capture; schedule one\n     *  fresh capture shortly after (once the animation settled) so the backdrop is the\n     *  clean wallpaper. */\n    void onLauncherFocused() {\n        // Extend the window opened by GestureToHome.  This does not pause Dock motion;\n        // only a new HOME SurfaceFlinger wrapper read is deferred below.\n        beginHomeSettle("launcher-focus");\n    }\n''',
'''    /** Called only from Launcher.onWindowFocusChanged(false).  Unlike lifecycle\n     * callbacks, this is authoritative evidence that HOME really left the foreground. */\n    void onLauncherFocusLost() {\n        if (Looper.myLooper() != Looper.getMainLooper()) {\n            mainHandler.post(this::onLauncherFocusLost);\n            return;\n        }\n        launcherWasAway = true;\n        // If a HOME return was interrupted back to an app, invalidate its delayed tail.\n        cancelHomeSettle("launcher-focus-lost");\n    }\n\n    /** Launcher gained real window focus.  Extend/arm the settle window only if the\n     * launcher actually was away (or GestureToHome already armed a genuine transition).\n     * A HOME-local Dock pull must never come through this path. */\n    void onLauncherFocused() {\n        if (Looper.myLooper() != Looper.getMainLooper()) {\n            mainHandler.post(this::onLauncherFocused);\n            return;\n        }\n        if (!launcherWasAway && !homeReturnTransitionArmed) {\n            cancelHomeSettle("launcher-focus-local");\n            return;\n        }\n        launcherWasAway = false;\n        armHomeSettle("launcher-focus");\n    }\n''',
"focus transition methods")

s = replace_once(s,
'''    private static final long HOME_SETTLE_MS = 650L;\n    private long homeSettleUntilNanos;\n    private boolean homeSettleCapturePending;\n\n    private boolean isHomeSettleActive() {\n        return System.nanoTime() < homeSettleUntilNanos;\n    }\n\n    private void beginHomeSettle(String reason) {\n        long until = System.nanoTime() + HOME_SETTLE_MS * 1_000_000L;\n        homeSettleUntilNanos = Math.max(homeSettleUntilNanos, until);\n        logI("home settle opened reason=" + reason);\n        scheduleHomeSettledCapture();\n    }\n\n    private void scheduleHomeSettledCapture() {\n        if (homeSettleCapturePending) return;\n        long remaining = homeSettleUntilNanos - System.nanoTime();\n        if (remaining <= 0L) {\n            requestStateCapture("home-settled");\n            return;\n        }\n        homeSettleCapturePending = true;\n        mainHandler.postDelayed(() -> {\n            homeSettleCapturePending = false;\n            if (!attached) return;\n            if (isHomeSettleActive()) {\n                scheduleHomeSettledCapture();\n                return;\n            }\n            updateDesiredScene();\n            if (sceneState.desired() == CaptureScene.HOME) {\n                requestStateCapture("home-settled");\n            }\n        }, Math.max(1L, (remaining + 999_999L) / 1_000_000L));\n    }\n''',
'''    private static final long HOME_SETTLE_MS = 650L;\n    private long homeSettleUntilNanos;\n    private boolean homeSettleCapturePending;\n\n    private boolean isHomeSettleActive() {\n        return homeReturnTransitionArmed && System.nanoTime() < homeSettleUntilNanos;\n    }\n\n    private void armHomeSettle(String reason) {\n        if (!homeReturnTransitionArmed) {\n            homeReturnTransitionArmed = true;\n            homeSettleGeneration++;\n        }\n        long until = System.nanoTime() + HOME_SETTLE_MS * 1_000_000L;\n        homeSettleUntilNanos = Math.max(homeSettleUntilNanos, until);\n        logI("home settle armed reason=" + reason + " generation=" + homeSettleGeneration);\n        scheduleHomeSettledCapture();\n    }\n\n    private void cancelHomeSettle(String reason) {\n        if (!homeReturnTransitionArmed && homeSettleUntilNanos == 0L\n                && !homeSettleCapturePending) return;\n        homeReturnTransitionArmed = false;\n        homeSettleUntilNanos = 0L;\n        homeSettleCapturePending = false;\n        // Existing Handler callbacks cannot be removed without retaining each Runnable.\n        // Generation invalidation makes them no-ops and prevents a stale home-settled\n        // frame from landing after a HOME-local spring-back.\n        homeSettleGeneration++;\n        logI("home settle cancelled reason=" + reason + " generation=" + homeSettleGeneration);\n    }\n\n    private void scheduleHomeSettledCapture() {\n        if (!homeReturnTransitionArmed || homeSettleCapturePending) return;\n        long remaining = homeSettleUntilNanos - System.nanoTime();\n        if (remaining <= 0L) {\n            homeReturnTransitionArmed = false;\n            homeSettleUntilNanos = 0L;\n            requestStateCapture("home-settled");\n            return;\n        }\n        homeSettleCapturePending = true;\n        final long generation = homeSettleGeneration;\n        mainHandler.postDelayed(() -> {\n            if (generation != homeSettleGeneration) return;\n            homeSettleCapturePending = false;\n            if (!attached || !homeReturnTransitionArmed) return;\n            if (isHomeSettleActive()) {\n                scheduleHomeSettledCapture();\n                return;\n            }\n            updateDesiredScene();\n            if (sceneState.desired() == CaptureScene.HOME) {\n                homeReturnTransitionArmed = false;\n                homeSettleUntilNanos = 0L;\n                requestStateCapture("home-settled");\n            } else {\n                cancelHomeSettle("settled-not-home");\n            }\n        }, Math.max(1L, (remaining + 999_999L) / 1_000_000L));\n    }\n''',
"generation-safe settle scheduler")

if "beginHomeSettle(" in s:
    raise SystemExit("obsolete beginHomeSettle call remains")
p.write_text(s, encoding="utf-8")

# MainHook: mark real window focus loss before resolving the foreground app layer.
p = Path("src/main/java/com/hellovoid/liquiddock/MainHook.java")
s = p.read_text(encoding="utf-8")
s = replace_once(s,
'''                    if (!hasFocus) {\n                        // An app came to the front: resolve its SF layer name so mode-1\n                        // captures can include exactly that layer.\n                        glass.refreshForegroundAppLayer();\n                    }\n''',
'''                    if (!hasFocus) {\n                        // Real Launcher window focus loss is the authoritative marker for\n                        // APP -> HOME detection later.  Do this before resolving the app.\n                        glass.onLauncherFocusLost();\n                        // An app came to the front: resolve its SF layer name so mode-1\n                        // captures can include exactly that layer.\n                        glass.refreshForegroundAppLayer();\n                    }\n''',
"focus-loss marker")
p.write_text(s, encoding="utf-8")

print("Applied scene-aware HOME settle false-positive fix")
