from pathlib import Path

VIEW = Path("src/main/java/com/hellovoid/liquiddock/Miuix307PassBlurTextureView.java")


def replace_once(old: str, new: str) -> None:
    text = VIEW.read_text()
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"expected one match, got {count}: {old[:140]!r}")
    VIEW.write_text(text.replace(old, new, 1))


replace_once(
    '''    private volatile int outputWidth;\n    private volatile int outputHeight;\n    private volatile int topOverscanPx = 48;''',
    '''    private volatile int outputWidth;\n    private volatile int outputHeight;\n    private volatile int maxTextureSize;\n    private volatile int topOverscanPx = 48;''')

replace_once(
    '''            makeCurrent();\n            ensureGlResources();\n            ensureFboSize(Math.max(1, width), Math.max(1, height));\n            drawLatestFrame(false);\n        } catch (Throwable error) {\n            fail("output attach", error);\n        }\n    }\n\n    private void destroyOutputWindow(Surface stale) {''',
    '''            makeCurrent();\n            queryMaxTextureSize();\n            // Mapping is View/screen geometry and therefore belongs on the UI thread. Do not\n            // allocate the first FBO until that mapping has been recomputed with the real GPU\n            // texture limit; otherwise one first frame could use capped FBOs with uncapped UVs.\n            mainHandler.post(() -> {\n                if (shuttingDown || outputWindowSurface != window) return;\n                updateBackdropMapping();\n                renderHandler.post(() -> finishOutputAttach(window, width, height));\n            });\n        } catch (Throwable error) {\n            fail("output attach", error);\n        }\n    }\n\n    private void finishOutputAttach(Surface window, int width, int height) {\n        if (shuttingDown || outputWindowSurface != window\n                || eglWindowSurface == EGL14.EGL_NO_SURFACE) return;\n        try {\n            makeCurrent();\n            ensureGlResources();\n            ensureFboSize(Math.max(1, width), Math.max(1, height));\n            drawLatestFrame(false);\n        } catch (Throwable error) {\n            fail("output attach finish", error);\n        }\n    }\n\n    private void queryMaxTextureSize() {\n        if (maxTextureSize > 0) return;\n        int[] value = new int[1];\n        GLES20.glGetIntegerv(GLES20.GL_MAX_TEXTURE_SIZE, value, 0);\n        if (value[0] <= 0) {\n            throw new IllegalStateException("GL_MAX_TEXTURE_SIZE unavailable");\n        }\n        maxTextureSize = value[0];\n        MainHook.log(TAG + " GL_MAX_TEXTURE_SIZE=" + maxTextureSize);\n    }\n\n    private void destroyOutputWindow(Surface stale) {''')

replace_once(
    '''    private SamplingInsets resolveSamplingInsets(int width, int height) {\n        int opticalX = Miuix307PrismalMaterial.requiredSampleGuardPx(\n                opticalParams, width, height, true);\n        int opticalY = Miuix307PrismalMaterial.requiredSampleGuardPx(\n                opticalParams, width, height, false);\n        int blurGuard = blurSamplingGuardPx();\n        opticalX += blurGuard;\n        opticalY += blurGuard;\n\n        int left = Math.max(horizontalOverscanPx() + Math.max(0, leftExtraOverscanPx), opticalX);\n        int right = Math.max(horizontalOverscanPx() + Math.max(0, rightExtraOverscanPx), opticalX);\n        int top = Math.max(Math.max(0, topOverscanPx), opticalY);\n        int bottom = Math.max(Math.max(0, bottomOverscanPx), opticalY);\n        return new SamplingInsets(left, right, top, bottom);\n    }\n\n    private void updateBackdropMapping() {''',
    '''    private SamplingInsets resolveSamplingInsets(int width, int height) {\n        int opticalX = Miuix307PrismalMaterial.requiredSampleGuardPx(\n                opticalParams, width, height, true);\n        int opticalY = Miuix307PrismalMaterial.requiredSampleGuardPx(\n                opticalParams, width, height, false);\n        int blurGuard = blurSamplingGuardPx();\n        opticalX += blurGuard;\n        opticalY += blurGuard;\n\n        int left = Math.max(horizontalOverscanPx() + Math.max(0, leftExtraOverscanPx), opticalX);\n        int right = Math.max(horizontalOverscanPx() + Math.max(0, rightExtraOverscanPx), opticalX);\n        int top = Math.max(Math.max(0, topOverscanPx), opticalY);\n        int bottom = Math.max(Math.max(0, bottomOverscanPx), opticalY);\n\n        int[] horizontal = fitInsetPairToTextureLimit(width, left, right, maxTextureSize);\n        int[] vertical = fitInsetPairToTextureLimit(height, top, bottom, maxTextureSize);\n        return new SamplingInsets(horizontal[0], horizontal[1], vertical[0], vertical[1]);\n    }\n\n    private static int[] fitInsetPairToTextureLimit(\n            int visible, int before, int after, int maxTextureSize) {\n        int safeVisible = Math.max(1, visible);\n        int safeBefore = Math.max(0, before);\n        int safeAfter = Math.max(0, after);\n        if (maxTextureSize <= 0) return new int[]{safeBefore, safeAfter};\n\n        int available = Math.max(0, maxTextureSize - safeVisible);\n        long desired = (long) safeBefore + safeAfter;\n        if (desired <= available) return new int[]{safeBefore, safeAfter};\n        if (available <= 0 || desired <= 0) return new int[]{0, 0};\n\n        int fittedBefore = (int) Math.round(safeBefore * (available / (double) desired));\n        fittedBefore = Math.max(0, Math.min(available, fittedBefore));\n        int fittedAfter = available - fittedBefore;\n        return new int[]{fittedBefore, fittedAfter};\n    }\n\n    private void updateBackdropMapping() {''')

replace_once(
    '''    private void ensureFboSize(int width, int height) {\n        SamplingInsets insets = resolveSamplingInsets(width, height);''',
    '''    private void ensureFboSize(int width, int height) {\n        if (maxTextureSize <= 0) {\n            throw new IllegalStateException("FBO allocation before GL_MAX_TEXTURE_SIZE query");\n        }\n        if (width > maxTextureSize || height > maxTextureSize) {\n            throw new IllegalStateException("visible material exceeds GL_MAX_TEXTURE_SIZE "\n                    + width + "x" + height + " max=" + maxTextureSize);\n        }\n        SamplingInsets insets = resolveSamplingInsets(width, height);''')
